// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Vof5hyP5IwfcnbOGcTUGGAdDAx_CFG4',
    appId: '1:164092993834:web:60d0199ff081f2e0a3fe53',
    messagingSenderId: '164092993834',
    projectId: 'studentmanagementapp-68ec0',
    authDomain: 'studentmanagementapp-68ec0.firebaseapp.com',
    storageBucket: 'studentmanagementapp-68ec0.appspot.com',
    measurementId: 'G-R5FKT86ZHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABUEVaIXECSPTHn5NZPnENmCrp-ZWYOwg',
    appId: '1:164092993834:android:8556f68332e878fca3fe53',
    messagingSenderId: '164092993834',
    projectId: 'studentmanagementapp-68ec0',
    storageBucket: 'studentmanagementapp-68ec0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC57kILpbRJjQbuYPgfPOJUONaqmOgwqQc',
    appId: '1:164092993834:ios:917f34cc13f124eaa3fe53',
    messagingSenderId: '164092993834',
    projectId: 'studentmanagementapp-68ec0',
    storageBucket: 'studentmanagementapp-68ec0.appspot.com',
    iosClientId: '164092993834-9sg288gii328di0julbh27ogthdpj8kc.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC57kILpbRJjQbuYPgfPOJUONaqmOgwqQc',
    appId: '1:164092993834:ios:0fc9042bd4e268afa3fe53',
    messagingSenderId: '164092993834',
    projectId: 'studentmanagementapp-68ec0',
    storageBucket: 'studentmanagementapp-68ec0.appspot.com',
    iosClientId: '164092993834-fkh00g39v3ftmuhfd8on6du60lrgf58s.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentManagementApp.RunnerTests',
  );
}
